feign:
  httpclient:
    disableSslValidation: true
    enabled: false
  okhttp:
    enabled: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mcb-rewards
    username: elite
    password: pwd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:

      # a day
      refresh-token:
        # 7 days

mcb-innov-app:
  points-conversion: 500
  username: hany
  password: P@ssw0rd
  base-url: https://mcbinovappapi.azurewebsites.net/
server:
  port: 8091

app:
  name: mcb-rewards
  version: 1
  description: Mcb InnovApp challenge for Elite Team